#ifndef ERRCODE_H_
#define ERRCODE_H_

#include "hiaiengine/status.h"

#define JDE_DEFINE_ERR 0x501

enum
{
    HIAI_INVALID_INPUT_MSG_CODE = 0,
    HIAI_JDE_MANAGER_INIT_FAIL_CODE,
    HIAI_JDE_MANAGER_PROCESS_FAIL_CODE,
    HIAI_JDE_CREATE_OUTPUT_FAIL_CODE,
    HIAI_JDE_CREATE_SHARED_PTR_FAIL_CODE
};

HIAI_DEF_ERROR_CODE(JDE_DEFINE_ERR, HIAI_ERROR, HIAI_INVALID_INPUT_MSG,
    "invalid input message pointer");
HIAI_DEF_ERROR_CODE(JDE_DEFINE_ERR, HIAI_ERROR, HIAI_JDE_MANAGER_INIT_FAIL,
    "ai model manager init fail");
HIAI_DEF_ERROR_CODE(JDE_DEFINE_ERR, HIAI_ERROR, HIAI_JDE_MANAGER_PROCESS_FAIL,
    "fail to process ai model manager");
HIAI_DEF_ERROR_CODE(JDE_DEFINE_ERR, HIAI_ERROR, HIAI_JDE_CREATE_OUTPUT_FAIL,
    "fail to create output tensor");
HIAI_DEF_ERROR_CODE(JDE_DEFINE_ERR, HIAI_ERROR, HIAI_JDE_CREATE_SHARED_PTR_FAIL,
    "fail to create shared pointer");

#endif