docker run --privileged --net=host \
--runtime nvidia \
--restart=always \
--entrypoint=/workspace/start_client.sh \
--name videoserver \
-v /mnt/data/:/mnt/data/ \
-v /data/docker_container_volume/algfw_client_log/:/var/log/sys/ \
--ulimit core=-1 -v /data/docker_container_volume/tmp:/tmp \
--log-opt max-size=10m \
--log-opt max-file=3 \
-d algfw_client_agx:1.0 172.1.1.254
