/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sihan_system_jni_utils_mot4j */

#ifndef _Included_com_sihan_system_jni_utils_mot4j
#define _Included_com_sihan_system_jni_utils_mot4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sihan_system_jni_utils_mot4j
 * Method:    load_mot_model
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sihan_system_jni_utils_mot4j_load_1mot_1model
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sihan_system_jni_utils_mot4j
 * Method:    unload_mot_model
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sihan_system_jni_utils_mot4j_unload_1mot_1model
  (JNIEnv *, jobject);

/*
 * Class:     com_sihan_system_jni_utils_mot4j
 * Method:    forward_mot_model
 * Signature: ([BIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sihan_system_jni_utils_mot4j_forward_1mot_1model
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
