/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sihan_system_jni_utils_TrackMerge */

#ifndef _Included_com_sihan_system_jni_utils_TrackMerge
#define _Included_com_sihan_system_jni_utils_TrackMerge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sihan_system_jni_utils_TrackMerge
 * Method:    get_registered_channels
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sihan_system_jni_utils_TrackMerge_get_1registered_1channels
  (JNIEnv *, jobject);

/*
 * Class:     com_sihan_system_jni_utils_TrackMerge
 * Method:    merge_track
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sihan_system_jni_utils_TrackMerge_merge_1track
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
